### ISSUE TITLE
[Airbase-NG] Segfaults for no reason?

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1761]
**Reported by CanadianJeff on 17 Nov 2015 11:16 UTC**

after about 10min of capture airbase-ng will segfault

```
root@kali:~# dpkg -l | grep aircrack-ng
ii  aircrack-ng                            1:1.2-0~rc2-0kali5                   amd64        wireless WEP/WPA cracking utilities
```

```
23:46:10  Got directed probe request from 2C:27:D7:FA:CD:22 - "SocialNature"
23:46:10  Got directed probe request from 2C:27:D7:FA:CD:22 - "SocialNature"
23:46:10  Got directed probe request from 2C:27:D7:FA:CD:22 - "SocialNature"
23:46:11  Got directed probe request from D8:EB:97:D0:D9:EB - "tnwh.ca - 170b"
23:46:12  Got directed probe request from 2C:27:D7:FA:CD:22 - "SocialNature"

Program received signal SIGSEGV, Segmentation fault.
[to Thread 0x7ffff6bfd700 (LWP 13634)](Switching)
__memcpy_ssse3 () at ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:2649
2649    ../sysdeps/x86_64/multiarch/memcpy-ssse3.S: No such file or directory.
(gdb) bt full
#0  __memcpy_ssse3 () at ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:2649
No locals.
#1  0x000055555555aed7 in ?? ()
No symbol table info available.
#2  0x00007ffff74c20a4 in start_thread (arg=0x7ffff6bfd700) at pthread_create.c:309
        __res = <optimized out>
        pd = 0x7ffff6bfd700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737333155584, -4176919623726318318, 1, 140737354125408, 140737488344688, 
                140737333155584, 4176935565019528466, 4176938174917197074}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 
              0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0```
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#3  0x00007ffff71f704d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.
```

**Comment by aircrack-ng** [comment]
**Comment by aircrack ng on 17 Nov 2015 23:46 UTC**

Could you provide the exact command you ran?

**Comment by aircrack-ng** [comment]
**Comment by CanadianJeff on 18 Nov 2015 15:51 UTC**

updating to latest version seems to have fixed the problem can close this issue now
