### ISSUE TITLE
airodump-ng: free() double free detected in tcache 2

### ISSUE THREAD

**Issue by ZerBea** [aircrack-ng/aircrack-ng#2134]
If configured with --disable-libnl, airodump-ng (latest git head) is running into double free error when terminating.
We detected this issue during latest driver tests: rtl8812au
https://github.com/aircrack-ng/rtl8812au/issues/587#issuecomment-600252419

**Comment by dmfreemon** [comment]
https://github.com/aircrack-ng/aircrack-ng/pull/2094

**Comment by ZerBea** [comment]
```
=================================================================
==67036==ERROR: AddressSanitizer: attempting double-free on 0x612000000040 in thread T0:
    #0 0x7f0e45c17720 in __interceptor_free /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:122
    #1 0x7f0e45af0bbd in do_free lib/osdep/linux.c:2288
    #2 0x555fb1d75fca in main src/airodump-ng/airodump-ng.c:7339
    #3 0x7f0e4538f022 in __libc_start_main (/usr/lib/libc.so.6+0x27022)
    #4 0x555fb1d79aed in _start (/home/zerobeat/temp/test/aircrack-ng/.libs/lt-airodump-ng+0x1baed)

0x612000000040 is located 0 bytes inside of 263-byte region [0x612000000040,0x612000000147)
freed by thread T0 here:
    #0 0x7f0e45c17720 in __interceptor_free /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:122
    #1 0x7f0e45af7780 in do_linux_open lib/osdep/linux.c:2262

previously allocated by thread T0 here:
    #0 0x7f0e45c17d48 in __interceptor_calloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:153
    #1 0x7f0e45af0e6c in searchInside lib/osdep/linux.c:211

SUMMARY: AddressSanitizer: double-free /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:122 in __interceptor_free
==67036==ABORTING

```

**Comment by dmfreemon** [comment]
I am not seeing this error while running with master (c4981c71) plus PR https://github.com/aircrack-ng/aircrack-ng/pull/2094

**Comment by ZerBea** [comment]
That issue report was made without PR https://github.com/aircrack-ng/aircrack-ng/pull/2094

**Comment by ZerBea** [comment]
Now applied the patch
https://github.com/aircrack-ng/aircrack-ng/pull/2094
from 10 Nov 2019.
Working fine. Good reason to close this report, because I used airodump-ng only to confirm a NETLINK related driver issue detected by hcxdumptool.
