### ISSUE TITLE
airodump-ng memory double-free

### ISSUE THREAD

**Issue by RafaelLeeImg** [aircrack-ng/aircrack-ng#2154]
# Issue type

- Defect - Crash
# System information

- OS: Debian testing
- CPU: Intel(R) Core(TM) i7-6700K

# Aircrack-ng version

- Version: master
- Commit Revision hash: 85754a8cb5fe8b87a24d1e88d961d81741019a5d

# Defect
## How to reproduce the issue
```bash
sudo ./airodump-ng wlan0mon
```
When program exits, it complains:
```bash
free(): double free detected in tcache 2
```

When compile and link with AddressSanitizer, add "-fsanitize=address" in CFLAGS, CXXFLAGS, LDFLAGS in Makefile, it shows that
```bash
==665629==ERROR: AddressSanitizer: attempting double-free on 0x6120000001c0 in thread T0:
    #0 0x7f20b9d05277 in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x107277)
    #1 0x7f20b9bd3da9 in do_free lib/osdep/linux.c:2288
    #2 0x7f20b9bd3f91 in linux_close lib/osdep/linux.c:2319
    #3 0x7f20b9bcbfba in wi_close lib/osdep/osdep.c:97
    #4 0x557f712a6f2a in main src/airodump-ng/airodump-ng.c:7339
    #5 0x7f20b969de0a in __libc_start_main ../csu/libc-start.c:308
    #6 0x557f712ac2d9 in _start (/dev/shm/d/aircrack-ng/.libs/airodump-ng+0x2b2d9)

0x6120000001c0 is located 0 bytes inside of 263-byte region [0x6120000001c0,0x6120000002c7)
freed by thread T0 here:
    #0 0x7f20b9d05277 in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x107277)
    #1 0x7f20b9bda40d in do_linux_open lib/osdep/linux.c:2262

previously allocated by thread T0 here:
    #0 0x7f20b9d0580e in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10780e)
    #1 0x7f20b9bd4121 in searchInside lib/osdep/linux.c:211

SUMMARY: AddressSanitizer: double-free (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x107277) in __interceptor_free
==665629==ABORTING
```

Then I found the problem is in lib/osdep/linux.c, line 1872
The pointer is assigned to dev->iwpriv, but when free, dev->iwpriv does not set to NULL.

```C
	dev->iwpriv = iwpriv;
```

**Comment by RafaelLeeImg** [comment]
Same to #2094
