### ISSUE TITLE
aircrack-ng segfaults on quitting (debian 3.1, kernel 2.6.22.1)

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#286]
**Reported by gabor on 7 Aug 2007 18:31 UTC**

So I run an instance of aircrack-ng. It's cracking. Then I press ctrl-c. This happens:

```
Quitting aircrack-ng...
Can't join thread 0

Quitting aircrack-ng...
```

At this point it just hangs here. Then I press ctrl-\. Now aircrack-ng segfaults:

```
Can't join thread 0
Segmentation fault (core dumped)
```

Backtrace (probably unhelpful):

```
#0  clean_exit (ret=0) at aircrack-ng.c:227
227                             if( ap_cur->ptw_clean->allsessions != NULL )
(gdb) bt
#0  clean_exit (ret=0) at aircrack-ng.c:227
#1  0x080525cc in sighandler (signum=3) at aircrack-ng.c:266
#2  0xb7ec8806 in __pthread_sighandler () from /lib/libpthread.so.0
#3  0xffffe420 in ?? ()
#4  0x00000003 in ?? ()
#5  0x00000033 in ?? ()
#6  0x00000000 in ?? ()
#7  0x0000007b in ?? ()
#8  0x0000007b in ?? ()
#9  0xb7ecc1d4 in __pthread_manager_request () from /lib/libpthread.so.0
#10 0xbff7825c in ?? ()
#11 0xbff78248 in ?? ()
#12 0xbff78248 in ?? ()
#13 0xbff7825c in ?? ()
#14 0xb7ecbff4 in ?? () from /lib/libpthread.so.0
#15 0x00000008 in ?? ()
#16 0xfffffffc in ?? ()
#17 0x00000000 in ?? ()
#18 0x00000000 in ?? ()
#19 0xb7ec5b64 in __pthread_sigsuspend () from /lib/libpthread.so.0
#20 0xb7ec4728 in __pthread_wait_for_restart_signal () from /lib/libpthread.so.0
#21 0xb7ec2783 in pthread_join () from /lib/libpthread.so.0
#22 0x08049925 in clean_exit (ret=-1209211744) at aircrack-ng.c:206
#23 0x080525ac in sighandler (signum=2) at aircrack-ng.c:280
#24 0xb7ec8806 in __pthread_sighandler () from /lib/libpthread.so.0
#25 0xffffe420 in ?? ()
#26 0x00000002 in ?? ()
#27 0x00000033 in ?? ()
#28 0x00000000 in ?? ()
#29 0xc010007b in ?? ()
#30 0xffff007b in ?? ()
#31 0x0805b140 in mx_ivb ()
#32 0x0000000d in ?? ()
#33 0xbff787e8 in ?? ()
#34 0xbff78770 in ?? ()
#35 0xbff78e30 in ?? ()
#36 0xbff78e30 in ?? ()
#37 0xfff820cd in ?? ()
```

**Comment by aircrack-ng** [comment]
**Comment by misterx on 7 Aug 2007 18:31 UTC**

Does earlier revisions also segfault?

**Comment by aircrack-ng** [comment]
**Comment by hirte on 7 Aug 2007 18:31 UTC**

would you please try the new revision?

**Comment by aircrack-ng** [comment]
**Comment by misterx on 7 Aug 2007 18:31 UTC**

If this bug still happen with most recent revisions, feel free to reopen it.

**Comment by aircrack-ng** [comment]
**Comment by gabor on 7 Aug 2007 18:31 UTC**

Works now. Didn't notice the ticket change due to email notify being off.
