### ISSUE TITLE
[patch] fix 'assert(*totlen);' core dump in openbsd.c

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#386]
**Reported by stsp on 12 Feb 2008 16:00 UTC**

With aircrack-ng 1.0-beta2 on OpenBSD-current as of Feb 2008, and Ralink chipset:

```
# ./aireplay-ng -9 ral0
16:37:28  Trying broadcast probe requests...
assertion "*totlen" failed: file "openbsd.c", line 170, function "get_80211"
Abort trap (core dumped)
```

Trace:

```
(gdb) bt
#0  0x07772269 in kill () from /usr/lib/libc.so.43.0
#1  0x077aa7f7 in abort () at /usr/src/lib/libc/stdlib/abort.c:68
#2  0x0774b817 in __assert2 (file=0x3c004853 "openbsd.c", line=170, func=0x3c004820 "get_80211", failedexpr=0x3c00486a "*totlen") at /usr/src/lib/libc/gen/assert.c:52
#3  0x1c00def7 in get_80211 ()
#4  0x1c00e110 in obsd_read ()
#5  0x1c00c8be in wi_read ()
#6  0x1c0018f2 in read_packet ()
#7  0x1c008e90 in do_attack_test ()
#8  0x1c00b845 in main ()
```

The problem seems to be this section in osdep/openbsd.c, obsd_read():
```
 	        /* need to read more */
 	        if (po->po_totlen == 0) {
 	                po->po_totlen = read(po->po_fd, po->po_buf, sizeof(po->po_buf));
 	                if (po->po_totlen == -1) {
 	                        po->po_totlen = 0;
 	                        return -1;
 	                }
 	                po->po_next = po->po_buf;
 	        }

 	        /* read 802.11 packet */
 	        wh = get_80211(po, &plen, ri);
```

If the call to read() above reads 0 bytes (and not -1 which only happens if an error occured), this assert in get_80211() is triggered: 
```
 	        totlen = &po->po_totlen;
 	        assert(*totlen);
```

The fix is simple, simply continue to read if there is no data yet for get_80211() to consume:
```
--- src/osdep/openbsd.c.orig    Fri Feb  1 23:50:24 2008
+++ src/osdep/openbsd.c Tue Feb 12 11:48:11 2008
@@ -238,7 +238,7 @@ static int obsd_read(struct wif *wi, unsigned char *h8
        assert(len > 0);
 
        /* need to read more */
-       if (po->po_totlen == 0) {
+       while (po->po_totlen == 0) {
                po->po_totlen = read(po->po_fd, po->po_buf, sizeof(po->po_buf));
                if (po->po_totlen == -1) {
                        po->po_totlen = 0;
```

With patch:

```
# ./aireplay-ng -9 ral0
16:38:06  Trying broadcast probe requests...
16:38:06  Injection is working!
16:38:07  Found 1 AP

16:38:07  Trying directed probe requests...
16:38:07  00:0D:3E:56:1B:B4 - channel: 1 - 'wlan'
16:38:16   0/30:   0%
```

**Comment by aircrack-ng** [comment]
**Comment by misterx on 12 Feb 2008 16:00 UTC**

It should be fixed by aircrack-ng/aircrack-ng@.

**Comment by aircrack-ng** [comment]
**Comment by misterx on 12 Feb 2008 16:00 UTC**

Closing the ticket now. Reopen it if it's not fixed.
