### ISSUE TITLE
OperationalError: database is locked

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#557]
**Reported by anonymous on 12 Dec 2008 14:43 UTC**

==== How to Reproduce ====

While doing a GET operation on `/roadmap`, Trac issued an internal error.

''(please provide additional details here)''

==== System Information ====

|| '''Trac''' || `0.11.1` ||
|| '''Python''' || `2.5.2 (aircrack-ng/aircrack-ng@925596df98eb1c2f83bb66c56f7e292ae244d815:60911, Nov 14 2008, 20:05:29) ` 
 `[4.3.2](GCC)` ||
|| '''setuptools''' || `0.6c8` ||
|| '''SQLite''' || `3.5.9` ||
|| '''pysqlite''' || `2.4.1` ||
|| '''Genshi''' || `0.5` ||
|| '''mod_python''' || `3.3.1` ||
|| '''Pygments''' || `0.10` ||
|| '''Subversion''' || `1.5.1 (aircrack-ng/aircrack-ng@)` ||

==== Python Traceback ====
```
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/trac/web/main.py", line 423, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/trac/web/main.py", line 222, in dispatch
    req.session.save()
  File "/usr/lib/python2.5/site-packages/trac/web/session.py", line 117, in save
    (self.last_visit, self.sid, authenticated))
  File "/usr/lib/python2.5/site-packages/trac/db/util.py", line 50, in execute
    return self.cursor.execute(sql_escape_percent(sql), args)
  File "/usr/lib/python2.5/site-packages/trac/db/sqlite_backend.py", line 58, in execute
    args or [])
  File "/usr/lib/python2.5/site-packages/trac/db/sqlite_backend.py", line 50, in _rollback_on_error
    return function(self, *args, **kwargs)
OperationalError: database is locked

```

**Comment by aircrack-ng** [comment]
**Modified by misterx on 12 Dec 2008 14:43 UTC**

**Comment by aircrack-ng** [comment]
**Comment by misterx on 12 Dec 2008 14:43 UTC**

Milestone N/A deleted
